Development
green-fox-academy/Self_Driving_Car pull request #3
Opened 2018-10-17 10:14 UTC by nandras88

All the sprints are completed.

http://jira.greenfox.academy/secure/RapidBoard.jspa?rapidView=38&projectKey=FLU&view=detail&selectedIssue=FLU-4

2018-10-19 11:33 UTC, leventekobor94 commented on sf_car/src/main.c
> +	MPU_InitStruct.BaseAddress = 0x20010000;
@nandras88 why this value?

2018-10-19 13:12 UTC, samsmith94 requested changes
- motor_forward_setup() and motor_backward_setup() funcitions should be inside 1 function, and find a better name for it. The code inside these functions doesn't refer to its usage. They are just gpio settings and these 2 functions are not called via touch screen buttons
- unneccessary new lines should be removed

2018-10-20 22:20 UTC, merged

2018-10-22 13:01 UTC, iringo commented on sf_car/src/main.c
> +GPIO_InitTypeDef motor_forward;  //engine turning forward
You meant here engine moving and not turning forward? Same in line 17?

2018-10-22 13:04 UTC, iringo commented on sf_car/src/main.c
> +volatile int x;
Maybe a more self-explanatory varibale name would be better here, like: x_coordinate_for_LCD or something similar.

2018-10-22 13:04 UTC, iringo commented on sf_car/src/main.c
> +	servo_handle.Init.Period = 2000;
Why exactly these concrete numbers? What is the logic behind it?

2018-10-22 13:05 UTC, iringo commented on sf_car/src/main.c
> +	servo_Config.Pulse = 145;
A very similar question why exactly 145 for the pulse?

2018-10-22 13:06 UTC, iringo commented on sf_car/src/main.c
> +	motor_backward.Pin = GPIO_PIN_10;
Why PIN10? Is this related to the motor's documentation? Same question for line 115!

2018-10-22 13:07 UTC, iringo commented on sf_car/src/main.c
> +	motor_handle.Init.Period = 1000;
Once again a similar question: why these exact numbers for the period and prescale?

2018-10-22 13:08 UTC, iringo commented on sf_car/src/main.c
> +	HAL_GPIO_WritePin(GPIOF, GPIO_PIN_10, GPIO_PIN_SET);
What function does this WritePin function serve?

2018-10-22 13:08 UTC, iringo commented on sf_car/src/main.c
> +				HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_0);
What is the purpose of these TogglePin functions?